import React from "react";
import "./Guide.css";
import search_logo from "../../images/search_logo.png";
import select_logo from "../../images/select_logo.png";
import standout_logo from "../../images/standout_logo.png";
const stepByStepGuideArr = [
  {
    logo: search_logo,
    title: "Search",
    desc: "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
  },
  {
    logo: select_logo,
    title: "Select",
    desc: "Choose from thousands of options generated by the slogan maker that fit your needs.",
  },
  {
    logo: standout_logo,
    title: "Stand out",
    desc: "Congrats on your new slogan. It's time to win the world!",
  },
];

function Guide() {
  return (
    <div className="guide_parent">
      {stepByStepGuideArr.map((value, ind) => (
        <div key={value.desc + ind} className="guide_container">
          <img src={value.logo} alt={value.title} />
          <h4 className="title">{value.title}</h4>
          <p className="description">{value.desc}</p>
        </div>
      ))}
    </div>
  );
}

export default Guide;
